### ISSUE TITLE
[Fix] Recoil `Duplicate atom key` error 해결

### ISSUE THREAD

**Issue by chmini** [prgrms-web-devcourse/Team_04_SFam_FE#144]
### 🚨 버그 설명

버그라고 해야하는지도 애매한데 동작에는 문제없지만 굉장히 거슬리는 메세지 로그입니다

https://github.com/facebookexperimental/Recoil/issues/733

### 🕹 실행 절차

로컬 서버를 실행하고 `userState`를 사용하는 페이지 이동 시 메세지가 뜹니다

### 📸 스크린샷

![image](https://user-images.githubusercontent.com/39076382/195786490-4486db22-5085-4c0d-a520-8c170af764bd.png)

**Comment by kyubumjang** [comment]
굉장히 거슬린 이슈군요. 해결이 돼서 다행입니다.
